name: Lint
on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize]
jobs:
  test:
    name: Run awesome linter
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v3
      with:
        node-version: 21
    - run: npx awesome-lint README.md
